--- #YAML:1.0
name:               PDF-OCR2
version:            1.20
abstract:           extract all text and all image ocr from pdf
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CAM::PDF:             1.52
    Carp:                 1
    Cwd:                  3
    Exporter:             5
    File::Path:           2.07
    File::PathInfo::Ext:  1.27
    File::Which:          0.05
    Image::OCR::Tesseract:  1.20
    LEOCHARRE::Class2:    1.19
    LEOCHARRE::CLI2:      1.07
    LEOCHARRE::Debug:     1.02
    LEOCHARRE::Dir:       1.07
    PDF::API2:            2.015
    PDF::Burst:           1.19
    PDF::GetImages:       1.17
    Test::Simple:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
