# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDF-OCR2
version:      1.13
version_from: lib/PDF/OCR2.pm
installdirs:  site
requires:
    CAM::PDF:                      1.50
    Carp:                          1
    Cwd:                           3
    File::PathInfo::Ext:           1.27
    Image::OCR::Tesseract:         1.20
    LEOCHARRE::Class2:             1.13
    LEOCHARRE::CLI2:               1.04
    LEOCHARRE::Dir:                1.06
    PDF::API2:                     2.015
    PDF::Burst:                    1.10
    PDF::GetImages:                1.10
    Smart::Comments:               1
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
