--- #YAML:1.0
name:                PDF-OCR2
version:             1.09
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    CAM::PDF:                      1.21
    Carp:                          1.04
    Cwd:                           3.12
    Image::OCR::Tesseract:         1.14
    LEOCHARRE::Class2:             1.11
    LEOCHARRE::DEBUG:              1.11
    LEOCHARRE::Dir:                1.02
    PDF::API2:                     2.015
    PDF::Burst:                    1.10
    PDF::GetImages:                1.01
    Smart::Comments:               1.0.2
    Test::Simple:                  0.8
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
